### ISSUE TITLE
Uncaught Error: Assertion failed

### ISSUE THREAD

**Issue by SignalsGriffiths** [patosai/tree-multiselect.js#114]
Uncaught Error: Assertion failed
    at i.assert (jquery.tree-multiselect.min.js:754:39)
    at jquery.tree-multiselect.min.js:254:40
    at jquery.tree-multiselect.min.js:257:31
    at Array.forEach (<anonymous>)
    at r.search (jquery.tree-multiselect.min.js:252:27)
    at HTMLInputElement.<anonymous> (jquery.tree-multiselect.min.js:482:35)
    at HTMLDivElement.dispatch (jquery-3.1.0.min.js:6:11741)
    at q.handle (jquery-3.1.0.min.js:6:9381)

This error is thrown when typing a 'space' into the search bar. Does anyone have any idea how to fix this? (The error doesn't stop the search it creates some untidy error logging)

**Comment by patosai** [comment]
Pretty interesting that no one has reported this error before, I tried it myself and replicated it. Should have a fix soon

**Comment by patosai** [comment]
Should be fixed in 2.6.3
